//**********************************************************************
//
// This skeleton was generated by abvkit at 2016-08-26 18:28:18 GMT
// from grammar '/home/tondy/dev/abvkit/grammars/hscript.peg'.
//
//**********************************************************************

package ;

class HscriptSemantics extends ParserBase.SemanticsBase {

  public function new()
  {
    super();
  }
  
  //-------------------------------------------------------------------
  // Invoked at the beginning of each invocation of the Parser.
  //-------------------------------------------------------------------
  public override function init()
  {
    super.init();
  }
  
}
