//**********************************************************************
//
// This skeleton was generated by abvkit at 2016-08-24 09:55:36 GMT
// from grammar '/home/tondy/dev/abvkit/grammars/hscript.peg'.
//
//**********************************************************************

package ;

class HscriptSemantics extends ParserBase.SemanticsBase {

  public function new()
  {
    super();
  }
}
